trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
jobs:
  - job: 
    displayName: Install Terraform
    steps:
    - task: TerraformTaskV1@0
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Internal Development - Brandon Hurlburt(0c249eea-065b-4034-955e-795d56b1e5d1)'
        backendAzureRmResourceGroupName: 'sandbox'
        backendAzureRmStorageAccountName: 'hurlburbdfutstorage'
        backendAzureRmContainerName: 'cfbfiles'
        backendAzureRmKey: 'tf/terraform.tfstate'
    